=== hchang19/capstone_project/cve_dataset/record_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Function Vulnerability Patch Record",
  "type": "object",
  "properties": {
    "func_name": {
      "type": "string",
      "description": "Name of the function"
    },
    "func_src_before": {
      "type": "string",
      "description": "Source code of the function with vulnerability."
    },
    "func_src_after": {
      "type": "string",
      "description": "Source code of the function with vulnerability patch"
    },
    "line_changes": {
      "type": "object",
      "properties": {
        "deleted": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "line_no": {
                "type": "integer",
                "description": "Line number where the change occurred"
              },
              "char_start": {
                "type": "integer",
                "description": "Starting character index of the change"
              },
              "char_end": {
                "type": "integer",
                "description": "Ending character index of the change"
              },
              "line": {
                "type": "string",
                "description": "Content of the deleted line"
              }
            },
            "required": ["line_no", "char_start", "char_end", "line"]
          }
        },
        "added": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "line_no": {
                "type": "integer",
                "description": "Line number where the change occurred"
              },
              "char_start": {
                "type": "integer",
                "description": "Starting character index of the change"
              },
              "char_end": {
                "type": "integer",
                "description": "Ending character index of the change"
              },
              "line": {
                "type": "string",
                "description": "Content of the added line"
              }
            },
            "required": ["line_no", "char_start", "char_end", "line"]
          }
        }
      },
      "required": ["deleted", "added"]
    },
    "char_changes": {
      "type": "object",
      "properties": {
        "deleted": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "char_start": {
                "type": "integer",
                "description": "Starting character index of the deleted characters"
              },
              "char_end": {
                "type": "integer",
                "description": "Ending character index of the deleted characters"
              },
              "chars": {
                "type": "string",
                "description": "Deleted characters"
              }
            },
            "required": ["char_start", "char_end", "chars"]
          }
        },
        "added": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "char_start": {
                "type": "integer",
                "description": "Starting character index of the added characters"
              },
              "char_end": {
                "type": "integer",
                "description": "Ending character index of the added characters"
              },
              "chars": {
                "type": "string",
                "description": "Added characters"
              }
            },
            "required": ["char_start", "char_end", "chars"]
          }
        }
      },
      "required": ["deleted", "added"]
    },
    "commit_link": {
      "type": "string",
      "description": "Link to the commit"
    },
    "file_name": {
      "type": "string",
      "description": "Name of the file"
    },
    "vul_type": {
      "type": "string",
      "description": "Type of the CWE vulnerability"
    }
  },
  "required": ["func_name", "func_src_before", "func_src_after", "line_changes", "char_changes", "commit_link", "file_name", "vul_type"]
}

=== hchang19/capstone_project/cve_dataset/cwe_787/record_43.json
{
    "func_name": "rfbProcessFileTransferReadBuffer",
    "func_src_before": "char *rfbProcessFileTransferReadBuffer(rfbClientPtr cl, uint32_t length)\n{\n    char *buffer=NULL;\n    int   n=0;\n\n    FILEXFER_ALLOWED_OR_CLOSE_AND_RETURN(\"\", cl, NULL);\n    /*\n    rfbLog(\"rfbProcessFileTransferReadBuffer(%dlen)\\n\", length);\n    */\n    if (length>0) {\n        buffer=malloc((uint64_t)length+1);\n        if (buffer!=NULL) {\n            if ((n = rfbReadExact(cl, (char *)buffer, length)) <= 0) {\n                if (n != 0)\n                    rfbLogPerror(\"rfbProcessFileTransferReadBuffer: read\");\n                rfbCloseClient(cl);\n                /* NOTE: don't forget to free(buffer) if you return early! */\n                if (buffer!=NULL) free(buffer);\n                return NULL;\n            }\n            /* Null Terminate */\n            buffer[length]=0;\n        }\n    }\n    return buffer;\n}",
    "func_src_after": "char *rfbProcessFileTransferReadBuffer(rfbClientPtr cl, uint32_t length)\n{\n    char *buffer=NULL;\n    int   n=0;\n\n    FILEXFER_ALLOWED_OR_CLOSE_AND_RETURN(\"\", cl, NULL);\n\n    /*\n       We later alloc length+1, which might wrap around on 32-bit systems if length equals\n       0XFFFFFFFF, i.e. SIZE_MAX for 32-bit systems. On 64-bit systems, a length of 0XFFFFFFFF\n       will safely be allocated since this check will never trigger and malloc() can digest length+1\n       without problems as length is a uint32_t.\n    */\n    if(length == SIZE_MAX) {\n\trfbErr(\"rfbProcessFileTransferReadBuffer: too big file transfer length requested: %u\", (unsigned int)length);\n\trfbCloseClient(cl);\n\treturn NULL;\n    }\n\n    if (length>0) {\n        buffer=malloc((size_t)length+1);\n        if (buffer!=NULL) {\n            if ((n = rfbReadExact(cl, (char *)buffer, length)) <= 0) {\n                if (n != 0)\n                    rfbLogPerror(\"rfbProcessFileTransferReadBuffer: read\");\n                rfbCloseClient(cl);\n                /* NOTE: don't forget to free(buffer) if you return early! */\n                if (buffer!=NULL) free(buffer);\n                return NULL;\n            }\n            /* Null Terminate */\n            buffer[length]=0;\n        }\n    }\n    return buffer;\n}",
    "line_changes": {
        "deleted": [
            {
                "line_no": 8,
                "char_start": 177,
                "char_end": 242,
                "line": "    rfbLog(\"rfbProcessFileTransferReadBuffer(%dlen)\\n\", length);\n"
            },
            {
                "line_no": 11,
                "char_start": 269,
                "char_end": 312,
                "line": "        buffer=malloc((uint64_t)length+1);\n"
            }
        ],
        "added": [
            {
                "line_no": 7,
                "char_start": 170,
                "char_end": 171,
                "line": "\n"
            },
            {
                "line_no": 9,
                "char_start": 178,
                "char_end": 269,
                "line": "       We later alloc length+1, which might wrap around on 32-bit systems if length equals\n"
            },
            {
                "line_no": 10,
                "char_start": 269,
                "char_end": 364,
                "line": "       0XFFFFFFFF, i.e. SIZE_MAX for 32-bit systems. On 64-bit systems, a length of 0XFFFFFFFF\n"
            },
            {
                "line_no": 11,
                "char_start": 364,
                "char_end": 465,
                "line": "       will safely be allocated since this check will never trigger and malloc() can digest length+1\n"
            },
            {
                "line_no": 12,
                "char_start": 465,
                "char_end": 514,
                "line": "       without problems as length is a uint32_t.\n"
            },
            {
                "line_no": 14,
                "char_start": 521,
                "char_end": 550,
                "line": "    if(length == SIZE_MAX) {\n"
            },
            {
                "line_no": 15,
                "char_start": 550,
                "char_end": 661,
                "line": "\trfbErr(\"rfbProcessFileTransferReadBuffer: too big file transfer length requested: %u\", (unsigned int)length);\n"
            },
            {
                "line_no": 16,
                "char_start": 661,
                "char_end": 682,
                "line": "\trfbCloseClient(cl);\n"
            },
            {
                "line_no": 17,
                "char_start": 682,
                "char_end": 696,
                "line": "\treturn NULL;\n"
            },
            {
                "line_no": 18,
                "char_start": 696,
                "char_end": 702,
                "line": "    }\n"
            },
            {
                "line_no": 19,
                "char_start": 702,
                "char_end": 703,
                "line": "\n"
            },
            {
                "line_no": 21,
                "char_start": 723,
                "char_end": 764,
                "line": "        buffer=malloc((size_t)length+1);\n"
            }
        ]
    },
    "char_changes": {
        "deleted": [
            {
                "char_start": 184,
                "char_end": 185,
                "chars": "L"
            },
            {
                "char_start": 221,
                "char_end": 224,
                "chars": "(%d"
            },
            {
                "char_start": 227,
                "char_end": 229,
                "chars": ")\\"
            },
            {
                "char_start": 246,
                "char_end": 248,
                "chars": "*/"
            },
            {
                "char_start": 292,
                "char_end": 293,
                "chars": "u"
            },
            {
                "char_start": 294,
                "char_end": 298,
                "chars": "nt64"
            }
        ],
        "added": [
            {
                "char_start": 170,
                "char_end": 171,
                "chars": "\n"
            },
            {
                "char_start": 182,
                "char_end": 192,
                "chars": "   We late"
            },
            {
                "char_start": 193,
                "char_end": 253,
                "chars": " alloc length+1, which might wrap around on 32-bit systems i"
            },
            {
                "char_start": 254,
                "char_end": 309,
                "chars": " length equals\n       0XFFFFFFFF, i.e. SIZE_MAX for 32-"
            },
            {
                "char_start": 310,
                "char_end": 350,
                "chars": "it systems. On 64-bit systems, a length "
            },
            {
                "char_start": 351,
                "char_end": 427,
                "chars": "f 0XFFFFFFFF\n       will safely be allocated since this check will never tri"
            },
            {
                "char_start": 428,
                "char_end": 557,
                "chars": "ger and malloc() can digest length+1\n       without problems as length is a uint32_t.\n    */\n    if(length == SIZE_MAX) {\n\trfbErr"
            },
            {
                "char_start": 591,
                "char_end": 603,
                "chars": ": too big fi"
            },
            {
                "char_start": 605,
                "char_end": 609,
                "chars": " tra"
            },
            {
                "char_start": 610,
                "char_end": 617,
                "chars": "sfer le"
            },
            {
                "char_start": 618,
                "char_end": 635,
                "chars": "gth requested: %u"
            },
            {
                "char_start": 638,
                "char_end": 652,
                "chars": "(unsigned int)"
            },
            {
                "char_start": 661,
                "char_end": 689,
                "chars": "\trfbCloseClient(cl);\n\treturn"
            },
            {
                "char_start": 690,
                "char_end": 696,
                "chars": "NULL;\n"
            },
            {
                "char_start": 699,
                "char_end": 702,
                "chars": " }\n"
            },
            {
                "char_start": 746,
                "char_end": 747,
                "chars": "s"
            },
            {
                "char_start": 748,
                "char_end": 750,
                "chars": "ze"
            }
        ]
    },
    "commit_link": "github.com/LibVNC/libvncserver/commit/15bb719c03cc70f14c36a843dcb16ed69b405707",
    "file_name": "libvncserver/rfbserver.c",
    "vul_type": "cwe-787"
}

=== hchang19/capstone_project/cve_dataset/cwe_787/record_42.json
{
    "func_name": "PHP_FUNCTION",
    "func_src_before": "PHP_FUNCTION(imagegammacorrect)\n{\n\tzval *IM;\n\tgdImagePtr im;\n\tint i;\n\tdouble input, output;\n\n\tif (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, \"rdd\", &IM, &input, &output) == FAILURE) {\n\t\treturn;\n\t}\n\n\tZEND_FETCH_RESOURCE(im, gdImagePtr, &IM, -1, \"Image\", le_gd);\n\n\tif (gdImageTrueColor(im))\t{\n\t\tint x, y, c;\n\n\t\tfor (y = 0; y < gdImageSY(im); y++)\t{\n\t\t\tfor (x = 0; x < gdImageSX(im); x++)\t{\n\t\t\t\tc = gdImageGetPixel(im, x, y);\n\t\t\t\tgdImageSetPixel(im, x, y,\n\t\t\t\t\tgdTrueColorAlpha(\n\t\t\t\t\t\t(int) ((pow((pow((gdTrueColorGetRed(c)   / 255.0), input)), 1.0 / output) * 255) + .5),\n\t\t\t\t\t\t(int) ((pow((pow((gdTrueColorGetGreen(c) / 255.0), input)), 1.0 / output) * 255) + .5),\n\t\t\t\t\t\t(int) ((pow((pow((gdTrueColorGetBlue(c)  / 255.0), input)), 1.0 / output) * 255) + .5),\n\t\t\t\t\t\tgdTrueColorGetAlpha(c)\n\t\t\t\t\t)\n\t\t\t\t);\n\t\t\t}\n\t\t}\n\t\tRETURN_TRUE;\n\t}\n\n\tfor (i = 0; i < gdImageColorsTotal(im); i++) {\n\t\tim->red[i]   = (int)((pow((pow((im->red[i]   / 255.0), input)), 1.0 / output) * 255) + .5);\n\t\tim->green[i] = (int)((pow((pow((im->green[i] / 255.0), input)), 1.0 / output) * 255) + .5);\n\t\tim->blue[i]  = (int)((pow((pow((im->blue[i]  / 255.0), input)), 1.0 / output) * 255) + .5);\n\t}\n\n\tRETURN_TRUE;\n}",
    "func_src_after": "PHP_FUNCTION(imagegammacorrect)\n{\n\tzval *IM;\n\tgdImagePtr im;\n\tint i;\n\tdouble input, output;\n\n\tif (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, \"rdd\", &IM, &input, &output) == FAILURE) {\n\t\treturn;\n\t}\n\n\tif ( input <= 0.0 || output <= 0.0 ) {\n\t\tphp_error_docref(NULL TSRMLS_CC, E_WARNING, \"Gamma values should be positive\");\n\t\tRETURN_FALSE;\n\t}\n\n\tZEND_FETCH_RESOURCE(im, gdImagePtr, &IM, -1, \"Image\", le_gd);\n\n\tif (gdImageTrueColor(im))\t{\n\t\tint x, y, c;\n\n\t\tfor (y = 0; y < gdImageSY(im); y++)\t{\n\t\t\tfor (x = 0; x < gdImageSX(im); x++)\t{\n\t\t\t\tc = gdImageGetPixel(im, x, y);\n\t\t\t\tgdImageSetPixel(im, x, y,\n\t\t\t\t\tgdTrueColorAlpha(\n\t\t\t\t\t\t(int) ((pow((pow((gdTrueColorGetRed(c)   / 255.0), input)), 1.0 / output) * 255) + .5),\n\t\t\t\t\t\t(int) ((pow((pow((gdTrueColorGetGreen(c) / 255.0), input)), 1.0 / output) * 255) + .5),\n\t\t\t\t\t\t(int) ((pow((pow((gdTrueColorGetBlue(c)  / 255.0), input)), 1.0 / output) * 255) + .5),\n\t\t\t\t\t\tgdTrueColorGetAlpha(c)\n\t\t\t\t\t)\n\t\t\t\t);\n\t\t\t}\n\t\t}\n\t\tRETURN_TRUE;\n\t}\n\n\tfor (i = 0; i < gdImageColorsTotal(im); i++) {\n\t\tim->red[i]   = (int)((pow((pow((im->red[i]   / 255.0), input)), 1.0 / output) * 255) + .5);\n\t\tim->green[i] = (int)((pow((pow((im->green[i] / 255.0), input)), 1.0 / output) * 255) + .5);\n\t\tim->blue[i]  = (int)((pow((pow((im->blue[i]  / 255.0), input)), 1.0 / output) * 255) + .5);\n\t}\n\n\tRETURN_TRUE;\n}",
    "line_changes": {
        "deleted": [],
        "added": [
            {
                "line_no": 12,
                "char_start": 204,
                "char_end": 244,
                "line": "\tif ( input <= 0.0 || output <= 0.0 ) {\n"
            },
            {
                "line_no": 13,
                "char_start": 244,
                "char_end": 326,
                "line": "\t\tphp_error_docref(NULL TSRMLS_CC, E_WARNING, \"Gamma values should be positive\");\n"
            },
            {
                "line_no": 14,
                "char_start": 326,
                "char_end": 342,
                "line": "\t\tRETURN_FALSE;\n"
            },
            {
                "line_no": 15,
                "char_start": 342,
                "char_end": 345,
                "line": "\t}\n"
            },
            {
                "line_no": 16,
                "char_start": 345,
                "char_end": 346,
                "line": "\n"
            }
        ]
    },
    "char_changes": {
        "deleted": [],
        "added": [
            {
                "char_start": 205,
                "char_end": 347,
                "chars": "if ( input <= 0.0 || output <= 0.0 ) {\n\t\tphp_error_docref(NULL TSRMLS_CC, E_WARNING, \"Gamma values should be positive\");\n\t\tRETURN_FALSE;\n\t}\n\n\t"
            }
        ]
    },
    "commit_link": "github.com/php/php-src/commit/1bd103df00f49cf4d4ade2cfe3f456ac058a4eae",
    "file_name": "ext/gd/gd.c",
    "vul_type": "cwe-787"
}

=== hchang19/capstone_project/cve_dataset/cwe_787/record_8.json
{
    "func_name": "ContentLine_Analyzer::DoDeliverOnce",
    "func_src_before": "int ContentLine_Analyzer::DoDeliverOnce(int len, const u_char* data)\n\t{\n\tconst u_char* data_start = data;\n\n\tif ( len <= 0 )\n\t\treturn 0;\n\n\tfor ( ; len > 0; --len, ++data )\n\t\t{\n\t\tif ( offset >= buf_len )\n\t\t\tInitBuffer(buf_len * 2);\n\n\t\tint c = data[0];\n\n#define EMIT_LINE \\\n\t{ \\\n\tbuf[offset] = '\\0'; \\\n\tint seq_len = data + 1 - data_start; \\\n\tseq_delivered_in_lines = seq + seq_len; \\\n\tlast_char = c; \\\n\tForwardStream(offset, buf, IsOrig()); \\\n\toffset = 0; \\\n\treturn seq_len; \\\n\t}\n\n\t\tswitch ( c ) {\n\t\tcase '\\r':\n\t\t\t// Look ahead for '\\n'.\n\t\t\tif ( len > 1 && data[1] == '\\n' )\n\t\t\t\t{\n\t\t\t\t--len; ++data;\n\t\t\t\tlast_char = c;\n\t\t\t\tc = data[0];\n\t\t\t\tEMIT_LINE\n\t\t\t\t}\n\n\t\t\telse if ( CR_LF_as_EOL & CR_as_EOL )\n\t\t\t\tEMIT_LINE\n\n\t\t\telse\n\t\t\t\tbuf[offset++] = c;\n\t\t\tbreak;\n\n\t\tcase '\\n':\n\t\t\tif ( last_char == '\\r' )\n\t\t\t\t{\n\t\t\t\t--offset; // remove '\\r'\n\t\t\t\tEMIT_LINE\n\t\t\t\t}\n\n\t\t\telse if ( CR_LF_as_EOL & LF_as_EOL )\n\t\t\t\tEMIT_LINE\n\n\t\t\telse\n\t\t\t\t{\n\t\t\t\tif ( ! suppress_weirds && Conn()->FlagEvent(SINGULAR_LF) )\n\t\t\t\t\tConn()->Weird(\"line_terminated_with_single_LF\");\n\t\t\t\tbuf[offset++] = c;\n\t\t\t\t}\n\t\t\tbreak;\n\n\t\tcase '\\0':\n\t\t\tif ( flag_NULs )\n\t\t\t\tCheckNUL();\n\t\t\telse\n\t\t\t\tbuf[offset++] = c;\n\t\t\tbreak;\n\n\t\tdefault:\n\t\t\tbuf[offset++] = c;\n\t\t\tbreak;\n\t\t}\n\n\t\tif ( last_char == '\\r' )\n\t\t\tif ( ! suppress_weirds && Conn()->FlagEvent(SINGULAR_CR) )\n\t\t\t\tConn()->Weird(\"line_terminated_with_single_CR\");\n\n\t\tlast_char = c;\n\t\t}\n\n\treturn data - data_start;\n\t}",
    "func_src_after": "int ContentLine_Analyzer::DoDeliverOnce(int len, const u_char* data)\n\t{\n\tconst u_char* data_start = data;\n\n\tif ( len <= 0 )\n\t\treturn 0;\n\n\tfor ( ; len > 0; --len, ++data )\n\t\t{\n\t\tif ( offset >= buf_len )\n\t\t\tInitBuffer(buf_len * 2);\n\n\t\tint c = data[0];\n\n#define EMIT_LINE \\\n\t{ \\\n\tbuf[offset] = '\\0'; \\\n\tint seq_len = data + 1 - data_start; \\\n\tseq_delivered_in_lines = seq + seq_len; \\\n\tlast_char = c; \\\n\tForwardStream(offset, buf, IsOrig()); \\\n\toffset = 0; \\\n\treturn seq_len; \\\n\t}\n\n\t\tswitch ( c ) {\n\t\tcase '\\r':\n\t\t\t// Look ahead for '\\n'.\n\t\t\tif ( len > 1 && data[1] == '\\n' )\n\t\t\t\t{\n\t\t\t\t--len; ++data;\n\t\t\t\tlast_char = c;\n\t\t\t\tc = data[0];\n\t\t\t\tEMIT_LINE\n\t\t\t\t}\n\n\t\t\telse if ( CR_LF_as_EOL & CR_as_EOL )\n\t\t\t\tEMIT_LINE\n\n\t\t\telse\n\t\t\t\tbuf[offset++] = c;\n\t\t\tbreak;\n\n\t\tcase '\\n':\n\t\t\tif ( last_char == '\\r' )\n\t\t\t\t{\n\t\t\t\t// Weird corner-case:\n\t\t\t\t// this can happen if we see a \\r at the end of a packet where crlf is\n\t\t\t\t// set to CR_as_EOL | LF_as_EOL, with the packet causing crlf to be set to\n\t\t\t\t// 0 and the next packet beginning with a \\n. In this case we just swallow\n\t\t\t\t// the character and re-set last_char.\n\t\t\t\tif ( offset == 0 )\n\t\t\t\t\t{\n\t\t\t\t\tlast_char = c;\n\t\t\t\t\tbreak;\n\t\t\t\t\t}\n\t\t\t\t--offset; // remove '\\r'\n\t\t\t\tEMIT_LINE\n\t\t\t\t}\n\n\t\t\telse if ( CR_LF_as_EOL & LF_as_EOL )\n\t\t\t\tEMIT_LINE\n\n\t\t\telse\n\t\t\t\t{\n\t\t\t\tif ( ! suppress_weirds && Conn()->FlagEvent(SINGULAR_LF) )\n\t\t\t\t\tConn()->Weird(\"line_terminated_with_single_LF\");\n\t\t\t\tbuf[offset++] = c;\n\t\t\t\t}\n\t\t\tbreak;\n\n\t\tcase '\\0':\n\t\t\tif ( flag_NULs )\n\t\t\t\tCheckNUL();\n\t\t\telse\n\t\t\t\tbuf[offset++] = c;\n\t\t\tbreak;\n\n\t\tdefault:\n\t\t\tbuf[offset++] = c;\n\t\t\tbreak;\n\t\t}\n\n\t\tif ( last_char == '\\r' )\n\t\t\tif ( ! suppress_weirds && Conn()->FlagEvent(SINGULAR_CR) )\n\t\t\t\tConn()->Weird(\"line_terminated_with_single_CR\");\n\n\t\tlast_char = c;\n\t\t}\n\n\treturn data - data_start;\n\t}",
    "line_changes": {
        "deleted": [],
        "added": [
            {
                "line_no": 52,
                "char_start": 1101,
                "char_end": 1124,
                "line": "\t\t\t\tif ( offset == 0 )\n"
            },
            {
                "line_no": 53,
                "char_start": 1124,
                "char_end": 1131,
                "line": "\t\t\t\t\t{\n"
            },
            {
                "line_no": 54,
                "char_start": 1131,
                "char_end": 1151,
                "line": "\t\t\t\t\tlast_char = c;\n"
            },
            {
                "line_no": 55,
                "char_start": 1151,
                "char_end": 1163,
                "line": "\t\t\t\t\tbreak;\n"
            },
            {
                "line_no": 56,
                "char_start": 1163,
                "char_end": 1170,
                "line": "\t\t\t\t\t}\n"
            }
        ]
    },
    "char_changes": {
        "deleted": [],
        "added": [
            {
                "char_start": 803,
                "char_end": 1174,
                "chars": "// Weird corner-case:\n\t\t\t\t// this can happen if we see a \\r at the end of a packet where crlf is\n\t\t\t\t// set to CR_as_EOL | LF_as_EOL, with the packet causing crlf to be set to\n\t\t\t\t// 0 and the next packet beginning with a \\n. In this case we just swallow\n\t\t\t\t// the character and re-set last_char.\n\t\t\t\tif ( offset == 0 )\n\t\t\t\t\t{\n\t\t\t\t\tlast_char = c;\n\t\t\t\t\tbreak;\n\t\t\t\t\t}\n\t\t\t\t"
            }
        ]
    },
    "commit_link": "github.com/bro/bro/commit/6c0f101a62489b1c5927b4ed63b0e1d37db40282",
    "file_name": "src/analyzer/protocol/tcp/ContentLine.cc",
    "vul_type": "cwe-787"
}

=== hchang19/capstone_project/cve_dataset/cwe_787/record_12.json
{
    "func_name": "input_csi_dispatch_sgr_colon",
    "func_src_before": "input_csi_dispatch_sgr_colon(struct input_ctx *ictx, u_int i)\n{\n\tstruct grid_cell\t*gc = &ictx->cell.cell;\n\tchar\t\t\t*s = ictx->param_list[i].str, *copy, *ptr, *out;\n\tint\t\t\t p[8];\n\tu_int\t\t\t n;\n\tconst char\t\t*errstr;\n\n\tfor (n = 0; n < nitems(p); n++)\n\t\tp[n] = -1;\n\tn = 0;\n\n\tptr = copy = xstrdup(s);\n\twhile ((out = strsep(&ptr, \":\")) != NULL) {\n\t\tif (*out != '\\0') {\n\t\t\tp[n++] = strtonum(out, 0, INT_MAX, &errstr);\n\t\t\tif (errstr != NULL || n == nitems(p)) {\n\t\t\t\tfree(copy);\n\t\t\t\treturn;\n\t\t\t}\n\t\t} else\n\t\t\tn++;\n\t\tlog_debug(\"%s: %u = %d\", __func__, n - 1, p[n - 1]);\n\t}\n\tfree(copy);\n\n\tif (n == 0)\n\t\treturn;\n\tif (p[0] == 4) {\n\t\tif (n != 2)\n\t\t\treturn;\n\t\tswitch (p[1]) {\n\t\tcase 0:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tbreak;\n\t\tcase 1:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tgc->attr |= GRID_ATTR_UNDERSCORE;\n\t\t\tbreak;\n\t\tcase 2:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tgc->attr |= GRID_ATTR_UNDERSCORE_2;\n\t\t\tbreak;\n\t\tcase 3:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tgc->attr |= GRID_ATTR_UNDERSCORE_3;\n\t\t\tbreak;\n\t\tcase 4:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tgc->attr |= GRID_ATTR_UNDERSCORE_4;\n\t\t\tbreak;\n\t\tcase 5:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tgc->attr |= GRID_ATTR_UNDERSCORE_5;\n\t\t\tbreak;\n\t\t}\n\t\treturn;\n\t}\n\tif (n < 2 || (p[0] != 38 && p[0] != 48 && p[0] != 58))\n\t\treturn;\n\tswitch (p[1]) {\n\tcase 2:\n\t\tif (n < 3)\n\t\t\tbreak;\n\t\tif (n == 5)\n\t\t\ti = 2;\n\t\telse\n\t\t\ti = 3;\n\t\tif (n < i + 3)\n\t\t\tbreak;\n\t\tinput_csi_dispatch_sgr_rgb_do(ictx, p[0], p[i], p[i + 1],\n\t\t    p[i + 2]);\n\t\tbreak;\n\tcase 5:\n\t\tif (n < 3)\n\t\t\tbreak;\n\t\tinput_csi_dispatch_sgr_256_do(ictx, p[0], p[2]);\n\t\tbreak;\n\t}\n}",
    "func_src_after": "input_csi_dispatch_sgr_colon(struct input_ctx *ictx, u_int i)\n{\n\tstruct grid_cell\t*gc = &ictx->cell.cell;\n\tchar\t\t\t*s = ictx->param_list[i].str, *copy, *ptr, *out;\n\tint\t\t\t p[8];\n\tu_int\t\t\t n;\n\tconst char\t\t*errstr;\n\n\tfor (n = 0; n < nitems(p); n++)\n\t\tp[n] = -1;\n\tn = 0;\n\n\tptr = copy = xstrdup(s);\n\twhile ((out = strsep(&ptr, \":\")) != NULL) {\n\t\tif (*out != '\\0') {\n\t\t\tp[n++] = strtonum(out, 0, INT_MAX, &errstr);\n\t\t\tif (errstr != NULL || n == nitems(p)) {\n\t\t\t\tfree(copy);\n\t\t\t\treturn;\n\t\t\t}\n\t\t} else {\n\t\t\tn++;\n\t\t\tif (n == nitems(p)) {\n\t\t\t\tfree(copy);\n\t\t\t\treturn;\n\t\t\t}\n\t\t}\n\t\tlog_debug(\"%s: %u = %d\", __func__, n - 1, p[n - 1]);\n\t}\n\tfree(copy);\n\n\tif (n == 0)\n\t\treturn;\n\tif (p[0] == 4) {\n\t\tif (n != 2)\n\t\t\treturn;\n\t\tswitch (p[1]) {\n\t\tcase 0:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tbreak;\n\t\tcase 1:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tgc->attr |= GRID_ATTR_UNDERSCORE;\n\t\t\tbreak;\n\t\tcase 2:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tgc->attr |= GRID_ATTR_UNDERSCORE_2;\n\t\t\tbreak;\n\t\tcase 3:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tgc->attr |= GRID_ATTR_UNDERSCORE_3;\n\t\t\tbreak;\n\t\tcase 4:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tgc->attr |= GRID_ATTR_UNDERSCORE_4;\n\t\t\tbreak;\n\t\tcase 5:\n\t\t\tgc->attr &= ~GRID_ATTR_ALL_UNDERSCORE;\n\t\t\tgc->attr |= GRID_ATTR_UNDERSCORE_5;\n\t\t\tbreak;\n\t\t}\n\t\treturn;\n\t}\n\tif (n < 2 || (p[0] != 38 && p[0] != 48 && p[0] != 58))\n\t\treturn;\n\tswitch (p[1]) {\n\tcase 2:\n\t\tif (n < 3)\n\t\t\tbreak;\n\t\tif (n == 5)\n\t\t\ti = 2;\n\t\telse\n\t\t\ti = 3;\n\t\tif (n < i + 3)\n\t\t\tbreak;\n\t\tinput_csi_dispatch_sgr_rgb_do(ictx, p[0], p[i], p[i + 1],\n\t\t    p[i + 2]);\n\t\tbreak;\n\tcase 5:\n\t\tif (n < 3)\n\t\t\tbreak;\n\t\tinput_csi_dispatch_sgr_256_do(ictx, p[0], p[2]);\n\t\tbreak;\n\t}\n}",
    "line_changes": {
        "deleted": [
            {
                "line_no": 21,
                "char_start": 485,
                "char_end": 494,
                "line": "\t\t} else\n"
            }
        ],
        "added": [
            {
                "line_no": 21,
                "char_start": 485,
                "char_end": 496,
                "line": "\t\t} else {\n"
            },
            {
                "line_no": 23,
                "char_start": 504,
                "char_end": 529,
                "line": "\t\t\tif (n == nitems(p)) {\n"
            },
            {
                "line_no": 24,
                "char_start": 529,
                "char_end": 545,
                "line": "\t\t\t\tfree(copy);\n"
            },
            {
                "line_no": 25,
                "char_start": 545,
                "char_end": 557,
                "line": "\t\t\t\treturn;\n"
            },
            {
                "line_no": 26,
                "char_start": 557,
                "char_end": 562,
                "line": "\t\t\t}\n"
            },
            {
                "line_no": 27,
                "char_start": 562,
                "char_end": 566,
                "line": "\t\t}\n"
            }
        ]
    },
    "char_changes": {
        "deleted": [],
        "added": [
            {
                "char_start": 493,
                "char_end": 495,
                "chars": " {"
            },
            {
                "char_start": 503,
                "char_end": 565,
                "chars": "\n\t\t\tif (n == nitems(p)) {\n\t\t\t\tfree(copy);\n\t\t\t\treturn;\n\t\t\t}\n\t\t}"
            }
        ]
    },
    "commit_link": "github.com/tmux/tmux/commit/a868bacb46e3c900530bed47a1c6f85b0fbe701c",
    "file_name": "input.c",
    "vul_type": "cwe-787"
}
